import Head from 'next/head';
import Link from 'next/link';

export default function Events({ title, data = [] }) {
  return (
    <>
      <Head>
        <title>{title || 'Hello World!'}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <nav>
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about-us'>About Us</Link>
        </nav>
      </header>
      <main>
        {data.map((i) => (
          <Link key={i?.id} href={i?.id ? `/events/${i?.id}` : '/'}>
            <img src={i?.image} alt={i?.description} />
            <h2>{i?.title}</h2>
            <p>{i?.description}</p>
          </Link>
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { events_categories } = await import('/data/data.json');
  return {
    props: {
      title: 'Hello every one',
      data: events_categories,
    },
  };
}
