import Head from 'next/head';
import Link from 'next/link';

export default function Header({ title }) {
  return (
    <>
      <Head>
        <title>{title || 'Events App - Nextjs'}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <nav>
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about-us'>About Us</Link>
        </nav>
      </header>
    </>
  );
}
